version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-node8-alpha
      
    working_directory: ~/repo
      
    steps:
      - checkout
      - run:
          name: Assemble & Test
          command: ./gradlew testRelease --console=plain
          environment:
            TERM: dumb